# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Behind Instin
email: nnicolaoss@gmail.com
description: On-going research about the «brouhaha literature» phenomena General Instin
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicolassauret.net/behindinstin/" # the base hostname & protocol for your site
twitter_username: nicolasauret
github_username:  lakonis

# Build settings
markdown: kramdown

timezone: Europe/Paris
